name: Update README

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count files and update README
        run: |
          # Install tree if not present (optional, for checking structure)
          sudo apt-get install -y tree
          echo "Repository structure:"
          tree

          # Initialize README content
          echo "# Question Summary" > README.md
          echo "" >> README.md

          # Function to count files in each directory
          count_files() {
            local dir_path="$1"
            local count=$(find "$dir_path" -type f -name "*.py" | wc -l)
            echo "$dir_path 刷了 $count 題" >> README.md
          }

          # Loop through all directories and count files
          for dir in $(find . -type d -not -path "./.git*"); do
            if [ "$(find "$dir" -type f -name "*.py" | wc -l)" -gt 0 ]; then
              dir_name=$(echo "$dir" | sed 's|^\./||' | sed 's|/| - |g')
              count_files "$dir"
            fi
          done

      - name: Commit and push README update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with question counts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
