name: Update README

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count files and update README
        run: |
          # Initialize README content
          echo "# Leetcode Summary" > README.md
          echo "" >> README.md

          # Initialize total count
          total_count=0

          # List of supported file extensions
          file_extensions=("*.py" "*.java")

          # Function to count files in each directory
          count_files() {
            local dir_path="$1"
            local dir_name="$2"
            local indent="$3"
            local count=0

            # Count files matching the extensions
            for ext in "${file_extensions[@]}"; do
              count=$((count + $(find "$dir_path" -type f -name "$ext" | wc -l)))
            done

            if [ "$count" -gt 0 ]; then
              echo "$indent- $dir_name solved $count problems" >> README.md
              total_count=$((total_count + count))
            fi
          }

          # Recursively count files in directories and subdirectories
          process_directory() {
            local parent_path="$1"
            local parent_name="$2"
            local indent="$3"
            
            count_files "$parent_path" "$parent_name" "$indent"
            
            for subdir in "$parent_path"/*/; do
              if [ -d "$subdir" ]; then
                local subdir_name=$(basename "$subdir")
                process_directory "$subdir" "$parent_name/$subdir_name" "  $indent"
              fi
            done
          }

          # Process top-level directories
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d -not -path "./.git*"); do
            dir_name=$(basename "$dir")
            process_directory "$dir" "$dir_name" ""
          done

          # Add total count to README
          echo "" >> README.md
          echo "A total of $total_count problems solved" >> README.md

      - name: Commit and push README update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "doc: Update README with question counts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
